### ISSUE TITLE
Ilastik fails on parallel processing of cores because of self-conflicts

### ISSUE THREAD

**Issue by ArtemSokolov** [labsyspharm/mcmicro#103]
This issue exists on O2 only, because all processes reference the same ilastik instance.

The issue does not exist in local runs, where ilastik instances are isolated from each other inside Docker containers.

One hypothesis is that ilastik locks the project file, preventing other ilastik processes from accessing it. A potential solution would be to replicate the project file for each image being classified.

```
Error executing process > 'ilastik (1)'

Caused by:
  Process `ilastik (1)` terminated with an error exit status (1)

Command executed:

  python /n/groups/lsp/mcmicro/2020-04-22/mcmicro-ilastik/CommandIlastikPrepOME.py --input 1.tif --output .       --num_channels `tail -n +2 markers.csv | wc -l`
  /n/groups/lsp/mcmicro/2020-04-22/ilastik-release/run_ilastik.sh --headless       --project=/n/groups/lsp/mcmicro/2020-04-22/mcmicro-ilastik/classifiers/exemplar_001.ilp *.hdf5

Command exit status:
  1

Command output:
  {'input': ['1.tif'], 'output': ['.'], 'crop': False, 'crop_size': None, 'nonzero_fraction': None, 'nuclei_index': None, 'num_channels': 40, 'ring_mask': False}
  Reading 1...
  Finished exporting image
  INFO lazyflow.operators.filterOperators: Using fast filters.
  INFO ilastik_main: Starting ilastik from "/n/groups/lsp/mcmicro/2020-04-22/ilastik-release".
  Starting ilastik from "/n/groups/lsp/mcmicro/2020-04-22/ilastik-release".
  INFO ilastik.shell.projectManager: Opening Project: /n/groups/lsp/mcmicro/2020-04-22/mcmicro-ilastik/classifiers/exemplar_001.ilp

Command error:
  WARNING __init__.py(20): UserWarning: init: Could not import tiktorch classifier
  WARNING 2020-04-22 21:17:01,393 opConservationTracking 78167 140433011181376 Could not find any ILP solver
  WARNING 2020-04-22 21:17:01,596 opStructuredTracking 78167 140433011181376 Could not find any ILP solver
  WARNING 2020-04-22 21:17:01,607 structuredTrackingWorkflow 78167 140433011181376 Could not find any learning solver. Tracking will use flow-based solver (DPCT). Learning for tracking will                                           be disabled!
  ERROR 2020-04-22 21:17:07,346 excepthooks 78167 140433011181376 Unhandled exception in thread: 'MainThread'
  ERROR 2020-04-22 21:17:07,356 excepthooks 78167 140433011181376 Traceback (most recent call last):
    File "/n/groups/lsp/mcmicro/2020-04-22/ilastik-release/ilastik-meta/ilastik/ilastik/shell/projectManager.py", line 150, in openProjectFile
      hdf5File = h5py.File(projectFilePath, mode)
    File "/n/groups/lsp/mcmicro/2020-04-22/ilastik-release/lib/python3.7/site-packages/h5py/_hl/files.py", line 394, in __init__
      swmr=swmr)
    File "/n/groups/lsp/mcmicro/2020-04-22/ilastik-release/lib/python3.7/site-packages/h5py/_hl/files.py", line 172, in make_fid
      fid = h5f.open(name, h5f.ACC_RDWR, fapl=fapl)
    File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
    File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
    File "h5py/h5f.pyx", line 85, in h5py.h5f.open
  OSError: Unable to open file (unable to lock file, errno = 11, error message = 'Resource temporarily unavailable')

  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
    File "/n/groups/lsp/mcmicro/2020-04-22/ilastik-release/ilastik-meta/ilastik/ilastik.py", line 134, in <module>
      main()
    File "/n/groups/lsp/mcmicro/2020-04-22/ilastik-release/ilastik-meta/ilastik/ilastik.py", line 128, in main
      hShell = ilastik_main.main(parsed_args, workflow_cmdline_args)
    File "/n/groups/lsp/mcmicro/2020-04-22/ilastik-release/ilastik-meta/ilastik/ilastik_main.py", line 165, in main
      f(shell)
    File "/n/groups/lsp/mcmicro/2020-04-22/ilastik-release/ilastik-meta/ilastik/ilastik_main.py", line 338, in loadProject
      shell.openProjectFile(path, parsed_args.readonly)
    File "/n/groups/lsp/mcmicro/2020-04-22/ilastik-release/ilastik-meta/ilastik/ilastik/shell/headless/headlessShell.py", line 94, in openProjectFile
      hdf5File, workflow_class, readOnly = ProjectManager.openProjectFile(projectFilePath, force_readonly)
    File "/n/groups/lsp/mcmicro/2020-04-22/ilastik-release/ilastik-meta/ilastik/ilastik/shell/projectManager.py", line 153, in openProjectFile
      hdf5File = h5py.File(projectFilePath, "r")
    File "/n/groups/lsp/mcmicro/2020-04-22/ilastik-release/lib/python3.7/site-packages/h5py/_hl/files.py", line 394, in __init__
      swmr=swmr)
    File "/n/groups/lsp/mcmicro/2020-04-22/ilastik-release/lib/python3.7/site-packages/h5py/_hl/files.py", line 170, in make_fid
      fid = h5f.open(name, flags, fapl=fapl)
    File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
    File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
    File "h5py/h5f.pyx", line 85, in h5py.h5f.open
  OSError: Unable to open file (unable to lock file, errno = 11, error message = 'Resource temporarily unavailable')
```

**Comment by ArtemSokolov** [comment]
Hypothesis confirmed. Fixed by #104
