### ISSUE TITLE
S3segmenter fails on non-TMA runs

### ISSUE THREAD

**Issue by DenisSch** [labsyspharm/mcmicro#26]
```
  Traceback (most recent call last):
    File "/app/S3segmenter.py", line 249, in <module>
      tissue_gauss1[tissue_gauss>np.percentile(tissue_gauss,99)]=np.nan
  ValueError: cannot convert float NaN to integer
```

Full error message:
```
executor >  local (3)
[-        ] process > illumination -
[49/711649] process > ashlar       [100%] 1 of 1 ✔
[-        ] process > dearray      -
[69/004d84] process > unmicst      [100%] 1 of 1 ✔
[4e/8e7af3] process > s3seg        [100%] 1 of 1, failed: 1 ✘
Error executing process > 's3seg (1)'

Caused by:
  Process `s3seg (1)` terminated with an error exit status (1)

Command executed:

  python /app/S3segmenter.py --crop noCrop        --imagePath exemplar-001.ome.tif        --maskPath NO_FILE        --nucleiClassProbPath exemplar-001_NucleiPM_1.tif        --contoursClassProbPath exemplar-001_ContoursPM_1.tif        --outputPath .

Command exit status:
  1

Command output:
  (empty)

Command error:
  48a6aaac4f1e: Pulling fs layer
  24817f242d67: Pulling fs layer
  96ad5f94f5f7: Pulling fs layer
  1de4a1760fb3: Pulling fs layer
  465553161802: Waiting
  48a6aaac4f1e: Waiting
  24817f242d67: Waiting
  96ad5f94f5f7: Waiting
  1de4a1760fb3: Waiting
  8ac92ddf84b3: Waiting
  a3ca60abc08a: Waiting
  c3b874b43f86: Waiting
  dea4ecac934f: Verifying Checksum
  dea4ecac934f: Download complete
  346ffb2b67d7: Verifying Checksum
  346ffb2b67d7: Download complete
  a3ca60abc08a: Verifying Checksum
  a3ca60abc08a: Download complete
  c3b874b43f86: Download complete
  8ac92ddf84b3: Verifying Checksum
  8ac92ddf84b3: Download complete
  48a6aaac4f1e: Verifying Checksum
  48a6aaac4f1e: Download complete
  465553161802: Verifying Checksum
  465553161802: Download complete
  24817f242d67: Verifying Checksum
  24817f242d67: Download complete
  dc65f448a2e2: Verifying Checksum
  dc65f448a2e2: Download complete
  1de4a1760fb3: Verifying Checksum
  1de4a1760fb3: Download complete
  dc65f448a2e2: Pull complete
  346ffb2b67d7: Pull complete
  dea4ecac934f: Pull complete
  96ad5f94f5f7: Verifying Checksum
  96ad5f94f5f7: Download complete
  8ac92ddf84b3: Pull complete
  a3ca60abc08a: Pull complete
  c3b874b43f86: Pull complete
  465553161802: Pull complete
  48a6aaac4f1e: Pull complete
  24817f242d67: Pull complete
  96ad5f94f5f7: Pull complete
  1de4a1760fb3: Pull complete
  Digest: sha256:4cdc3b60ec11ac974e5f3bfbed4abffb02ebedd2b9f3461a91a25480c2493140
  Status: Downloaded newer image for labsyspharm/s3segmenter:latest
  Traceback (most recent call last):
    File "/app/S3segmenter.py", line 249, in <module>
      tissue_gauss1[tissue_gauss>np.percentile(tissue_gauss,99)]=np.nan
  ValueError: cannot convert float NaN to integer

Work dir:
  /Users/denis/work/4e/8e7af38968b046f70c79754c9a1ba8

Tip: you can try to figure out what's wrong by changing to the process work dir and showing the script file named `.command.sh`
```

**Comment by ArtemSokolov** [comment]
Thanks, Denis. This is a known issue, and Clarence is working on addressing it.

S3segmenter currently only works with `--TMA`.

**Comment by ArtemSokolov** [comment]
This was addressed in a [recent fix pushed to S3segmenter](https://github.com/HMS-IDAC/S3segmenter/commit/ebdb389d3039f858301e764efdf444b78ab489fa).
