### ISSUE TITLE
Question about unmicst model names

### ISSUE THREAD

**Issue by keller-mark** [labsyspharm/mcmicro#276]
Hi,
The pipeline has been working very well! However, I am running on mouse data and saw that there is a note about a mouse nuclei UnMicst model in the documentation

> --model
> The name of the UNet model. By default, this is the human nuclei model that identifies nuclei centers, nuclei contours, and background from a DAPI channel. Other models include mouse nuclei from DAPI, and cytoplasm from stains resembling WGA

https://mcmicro.org/parameter-reference.html#arguments-to-unmicst--unmicst-opts

 I tried using `--unmicst-opts '--model mousenucleiDAPI'` but this resulted in the following error:

```
Error executing process > 'probmaps:unmicst (1)'

Caused by:
  Missing output file(s) `*Probabilities*.tif` expected by process `probmaps:unmicst (1)`

Command executed:

  python /app/unmicstWrapper.py lung.ome.tif --scalingFactor 1 --model mousenucleiDAPI --stackOutput --outputPath .

Command exit status:
  0

Command output:
  Using CPU
  loading data
  loading data
  loading data
  0.0942104550464887
  0.08848931361402539

  WARNING! USING V1.5 AS DEFAULT. THIS MODEL HAS BEEN TRAINED ON MORE TISSUE TYPES. IF YOU WANT V1, USE --tool UnMicst

  python /app/UnMicst1-5.py  lung.ome.tif --channel 0 --outputPath . --mean -1 --std -1 --scalingFactor 1.0 --GPU -1 --outlier -1 --stackOutput  --model mousenucleiDAPI

Command error:
    File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/training/saver.py", line 1300, in restore
      names_to_keys = object_graph_key_mapping(save_path)
    File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/training/saver.py", line 1618, in object_graph_key_mapping
      object_graph_string = reader.get_tensor(trackable.OBJECT_GRAPH_PROTO_KEY)
    File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/training/py_checkpoint_reader.py", line 74, in get_tensor
      error_translator(e)
    File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/training/py_checkpoint_reader.py", line 35, in error_translator
      raise errors_impl.NotFoundError(None, None, error_message)
  tensorflow.python.framework.errors_impl.NotFoundError: Key _CHECKPOINTABLE_OBJECT_GRAPH not found in checkpoint

  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
    File "/app/UnMicst1-5.py", line 758, in <module>
      UNet2D.singleImageInferenceSetup(modelPath, GPU, args.mean, args.std)
    File "/app/UnMicst1-5.py", line 680, in singleImageInferenceSetup
      saver.restore(UNet2D.Session, variablesPath)
    File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/training/saver.py", line 1306, in restore
      err, "a Variable name or other graph key that is missing")
```

Is the mouse model under a different name? Or is this model only applicable to a specific UnMicst version?

**Comment by clarenceyapp** [comment]
Hi @keller-mark , please add `--tool UnMicst --classOrder 1 0 2` to the list of options. We recently made UnMicst1.5 the default and that has now broken this. We will update the documentation accordingly.

I should also mention that the mouse model was trained on a very limited training set (mouse brain and small intestine) for a specific project. So the applicability of this model may be limited.

**Comment by ArtemSokolov** [comment]
To clarify, the options Clarence listed would go into `--unmicst-opts`. The full command would look like

```
nextflow run labsyspharm/mcmicro --in /path/to/data --unmicst-opts '--tool UnMicst --classOrder 1 0 2'
```

**Comment by keller-mark** [comment]
Thanks!
