### ISSUE TITLE
[s3seg] xmlschema check too strict

### ISSUE THREAD

**Issue by Mr-Milk** [labsyspharm/mcmicro#356]
When running `s3seg` step, my input image has an XML field `AcquisitionData` which crash the run.

I tried opened this image with bio-format plugins in imageJ and it has no problem.

```
Error executing process > 'segmentation:s3seg (4)'

Caused by:
  Process `segmentation:s3seg (4)` terminated with an error exit status (1)

Command executed:

  python /app/S3segmenter.py         --imagePath 37.ome.tiff --stackProbPath 37_Probabilities_9.tif          --outputPath .

Command exit status:
  1

Command output:
  (empty)

Command error:
    File "/usr/local/lib/python3.7/site-packages/xmlschema/validators/schema.py", line 1949, in decod
      for result in self.iter_decode(source, path, schema_path, validation, *args, **kwargs):
    File "/usr/local/lib/python3.7/site-packages/xmlschema/validators/schema.py", line 1937, in iter_decode
      yield from xsd_element.iter_decode(elem, validation, **kwargs)
    File "/usr/local/lib/python3.7/site-packages/xmlschema/validators/elements.py", line 651, in iter_decode
      for result in content_decoder.iter_decode(elem, validation, **kwargs):
    File "/usr/local/lib/python3.7/site-packages/xmlschema/validators/groups.py", line 762, in iter_decode
      for result in xsd_element.iter_decode(child, validation, **kwargs):
    File "/usr/local/lib/python3.7/site-packages/xmlschema/validators/elements.py", line 651, in iter_decode
      for result in content_decoder.iter_decode(elem, validation, **kwargs):
    File "/usr/local/lib/python3.7/site-packages/xmlschema/validators/groups.py", line 785, in iter_decode
      yield self.children_validation_error(validation, elem, *model_error, **kwargs)
    File "/usr/local/lib/python3.7/site-packages/xmlschema/validators/groups.py", line 246, in children_validation_error
      raise error
  xmlschema.validators.exceptions.XMLSchemaChildrenValidationError: failed validating <Element '{http://www.openmicroscopy.org/Schemas/OME/2016-06}Image' at 0x7fa8634764d0> with XsdGroup(model='sequence', occurs=[1, 1]):

  Reason: Unexpected child with tag 'OME:AcquisitionDate' at position 2.

  Schema:

    <xsd:complexType xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <xsd:sequence>
        <xsd:element maxOccurs="1" minOccurs="0" name="AcquisitionDate" type="xsd:dateTime">
          <xsd:annotation>
            <xsd:documentation>
              The acquisition date of the Image.
              The element contains an xsd:dateTime string based on the ISO 8601 format (i.e. 1988-04-07T18:39:09.359)

              YYYY-MM-DDTHH:mm:SS.sssZ
              Y - Year
              M - Month
              D - Day
              H - Hour
              m - minutes
              S - Seconds
              s - sub-seconds (optional)
              Z - Zone (optional) +HH:mm or -HH:mm or Z for UTC

              Note: xsd:dataTime supports a very wide date range with unlimited precision. The full date range
              and precision are not typically supported by platform- and language-specific libraries.
      ...
      ...
    </xsd:complexType>

  Instance:

<Image xmlns="http://www.openmicroscopy.org/Schemas/OME/2016-06" ID="Image:0" Name="01122022 BPH 373 small panel_s0_a47_ac.ome.tiff">
<Pixels BigEndian="false" DimensionOrder="XYCZT" ID="Pixels:0" Interleaved="true" SizeC="10" SizeT="1" SizeX="650" SizeY="650" SizeZ="1" Type="float">
<Channel Fluor="Pr141" ID="Channel:0:0" Name="141Pr" SamplesPerPixel="1" />
<Channel Fluor="Nd143" ID="Channel:0:1" Name="143Nd" SamplesPerPixel="1" />
<Channel Fluor="Nd148" ID="Channel:0:2" Name="148Nd" SamplesPerPixel="1" />
<Channel Fluor="Gd152" ID="Channel:0:3" Name="152Gd" SamplesPerPixel="1" />
<Channel Fluor="Sm152" ID="Channel:0:4" Name="152Sm" SamplesPerPixel="1" />
<Channel Fluor="Gd158" ID="Channel:0:5" Name="158Gd" SamplesPerPixel="1" />
<Channel Fluor="Tb159" ID="Channel:0:6" Name="159Tb" SamplesPerPixel="1" />
<Channel Fluor="Tm169" ID="Channel:0:7" Name="169Tm" SamplesPerPixel="1" />
<Channel Fluor="Ir191" ID="Channel:0:8" Name="191Ir" SamplesPerPixel="1" />
<Channel Fluor="Ir193" ID="Channel:0:9" Name="193Ir" SamplesPerPixel="1" />
<TiffData />
</Pixels>
<AcquisitionDate>2022-01-13T22:37:07.259974+08:00</AcquisitionDate>   <-- Failed to pass the check
</Image>

  Path: /OME/Image

Work dir:
  /.../work/05/ecbc404e342314fdc0d040d2537305

Tip: you can replicate the issue by changing to the process work dir and entering the command `bash .command.run`
```

**Comment by ArtemSokolov** [comment]
Hi @Mr-Milk,

This is likely triggered by `ome_types.from_xml()`, which we use to parse metadata in OME-TIFF files.
Can you do a quick check whether the following works with your image?

``` python
import tifffile, ome_types
tif = tifffile.TiffFile('yourimage.ome.tif')
meta = ome_types.from_xml(tif.ome_metadata)
```

Unfortunately, [from_xml()](https://ome-types.readthedocs.io/en/latest/ome_types.html#ome_types.from_xml) doesn't provide any additional parameters to control the level of strictness. However, any file that passes [xmlvalid from the Bio-Formats command line tools](https://docs.openmicroscopy.org/ome-model/6.2.2/ome-tiff/tools.html#validating-ome-xml) should theoretically work.

How is your OME-TIFF file generated? Does it pass the `xmlvalid` check?

**Comment by Mr-Milk** [comment]
It failed with the same error message, the images are IMC images generated with [imctools](https://github.com/BodenmillerGroup/imctools) which is a known issue BodenmillerGroup/imctools#114

I may just delete the fields that fail the check and proceed.

Thanks for the help!

**Comment by fuerzhou** [comment]
Hi @Mr-Milk ,

I have got another XML related error when running s3seg
```
ERROR ~ Error executing process > 'segmentation:s3seg (1)'

Caused by:
  Process `segmentation:s3seg (1)` terminated with an error exit status (1)

Command executed:

  python /app/S3segmenter.py         --imagePath T-Cell-tonsil_[55721,14924]-crop.ome.tiff --stackProbPath T-Cell-tonsil_[55721,14924]-crop_Probabilities_1.tif           --outputPath .

Command exit status:
  1

Command output:
  (empty)

Command error:
  /app/S3segmenter.py:18: DeprecationWarning: Please use `uniform_filter` from the `scipy.ndimage` namespace, the `scipy.ndimage.filters` namespace is deprecated.
    from scipy.ndimage.filters import uniform_filter
  Traceback (most recent call last):
    File "/app/S3segmenter.py", line 398, in <module>
      metadata = getMetadata(imagePath,commit)
    File "/app/S3segmenter.py", line 139, in getMetadata
      metadata=ome_types.from_xml(tif.ome_metadata)
    File "/usr/local/lib/python3.8/site-packages/ome_types/_convenience.py", line 24, in from_xml
      d = to_dict(xml)
    File "/usr/local/lib/python3.8/site-packages/ome_types/schema.py", line 231, in to_dict
      schema = schema or get_schema(xml)
    File "/usr/local/lib/python3.8/site-packages/ome_types/schema.py", line 78, in get_schema
      raise XMLSchemaValueError(f"Could not find a schema for XML resource {source!r}.")
  xmlschema.exceptions.XMLSchemaValueError: Could not find a schema for XML resource XMLResource(root=<Element '{http://www.openmicroscopy.org/Schemas/OME/2016-06}OME' at 0x7fde850a62c0>).
  ```
  
  I tried checking it with the following code as you mentioned above and there was no error.
```
import tifffile, ome_types
tif = tifffile.TiffFile('yourimage.ome.tif')
meta = ome_types.from_xml(tif.ome_metadata)
```

The metadata also passes xml valid check.
Could you please help with the issue?

Thank you!
Yuzhou

**Comment by ArtemSokolov** [comment]
Hi @fuerzhou,

What version of `ome_types` did you use to run the check (the one that passed)? It's possible that we need to update the package inside the `s3seg` container, if there have been recent changes to the metadata standards and images are now following the new standards.

**Comment by fuerzhou** [comment]
Hi @ArtemSokolov,

Thank you for the prompt reply. I used `ome_types-0.4.5`

**Comment by ArtemSokolov** [comment]
Thanks, @fuerzhou. I just updated `ome_types` to 0.4.5 inside the `s3seg` container.
Can you try pulling the new version of the pipeline with `nextflow pull labsyspharm/mcmicro` and then trying your image again?

**Comment by fuerzhou** [comment]
Thanks @ArtemSokolov for the speedy update. What is the version of s3seg image you've updated? I pulled the image 1.5.5 but it had the same error.

**Comment by ArtemSokolov** [comment]
Should be `1.5.6` from this PR: https://github.com/labsyspharm/mcmicro/pull/532/files

**Comment by fuerzhou** [comment]
I was using our HPC and it uses singularity to pull the image. I'm not sure if the update is synced with singularity?

**Comment by fuerzhou** [comment]
It works now. Thank you again for the help!
