### ISSUE TITLE
Channels metadata info in sequential staining

### ISSUE THREAD

**Issue by asmagen** [labsyspharm/mcmicro#377]
I'm trying to apply the method on sequential staining (MICSSS) and so far I encountered the following issues:

1. When using a pre-registered tile (one PNG file for each marker) and following the advise in this [earlier issue](https://github.com/labsyspharm/mcmicro/issues/338) I run and get the following:
```nextflow run ../main.nf --in 1003_bx -profile minerva --single-formats png --start-at probability-maps
N E X T F L O W  ~  version 20.10.0
Launching `../main.nf` [shrivelled_ramanujan] - revision: e375cef610
executor >  lsf (3)
[-        ] process > illumination                    -
executor >  lsf (3)
[-        ] process > illumination                    -
[-        ] process > registration:ashlar             -
[-        ] process > dearray:coreograph              -
[ae/d317a7] process > segmentation:worker (unmicst-1) [100%] 1 of 1 ✔
[88/0b2462] process > segmentation:s3seg (1)          [100%] 1 of 1 ✔
[c8/5fdd51] process > quantification:mcquant (1)      [100%] 1 of 1, failed: 1 ✘
[-        ] process > cellstates:worker               -
Error executing process > 'quantification:mcquant (1)'

Caused by:
  Process `quantification:mcquant (1)` terminated with an error exit status (1)

Command executed:

  python /app/CommandSingleCellExtraction.py --image unmicst-1003_bx.ome.tif     --masks cell*.tif --output . --channel_names markers.csv

Command exit status:
  1

Command output:
  {'masks': ['cell.ome.tif'], 'image': 'unmicst-1003_bx.ome.tif', 'channel_names': 'markers.csv', 'output': '.', 'intensity_props': {'intensity_mean'}, 'mask_props': None}
  Extracting single-cell data for unmicst-1003_bx.ome.tif...

Command error:
  Traceback (most recent call last):
    File "/app/CommandSingleCellExtraction.py", line 11, in <module>
      SingleCellDataExtraction.MultiExtractSingleCells(**args)
    File "/app/SingleCellDataExtraction.py", line 263, in MultiExtractSingleCells
      ExtractSingleCells(masks,image,channel_names,output, mask_props=mask_props, intensity_props=intensity_props)
    File "/app/SingleCellDataExtraction.py", line 215, in ExtractSingleCells
      raise Exception("The number of channels in %s doesn't match the image"%channel_names)
  Exception: The number of channels in markers.csv doesn't match the image

Work dir:
  /sc/arion/scratch/magena01/mcmicro/testing/work/c8/5fdd5130d8e080f4d635f9c3822395

Tip: view the complete command output by changing to the process work dir and entering the command `cat .command.out`
```
I tried having the markers file list each marker (corresponding to different files, not image channels) or alternatively just one row named 'all' to indicate that each image has one stain, but both fail. How do I indicate the image channels in this example of a single stain per png image?

2. Not sure if it would be possible to use the original SVS files as input (not registered)?

Thank you

**Comment by ArtemSokolov** [comment]
Hi @asmagen,

1. Can you share what your `markers.csv` looks like? Also, how many channels does `unmicst-1003_bx.ome.tif` have?

2. We haven't tested the pipeline with .svs files, but they appear to be bio-formats compatible, so it should work theoretically. You can tell [MCMICRO what formats to look for explicitly](https://mcmicro.org/instructions/faq.html#q-mcmicro-doesnt-seem-to-recognize-my-file-format-how-do-i-tell-it-what-files-to-look-for) in the `raw/` folder.

**Comment by asmagen** [comment]
I tried a file containing:
cycle,marker_name
1,CD3
2,CD8
3,FOXP3
4,CD20

as well as
cycle,marker_name
1,all

and both failed with the error I mentioned in the thread.

**Comment by Yu-AnChen** [comment]
It seems like you are working with multiplexed IHC type of method and generating brightfield images. The SVS files are likely already stitched. Currently, I would suggest using [palom](https://github.com/Yu-AnChen/palom) to generate a "registered" image (ome-tiff), place the ome-tiff in the [`registration` directory](https://mcmicro.org/instructions/nextflow/#output) and start the pipeline from the segmentation step. 

To solve the `markers.csv` validation issue, please inspect the ome-tiff with fiji or qupath to see how many channels are in the output file - the `markers.csv` must have the same number of rows (excluding the header).

**Comment by asmagen** [comment]
But I already have very well registered images, a process I would really like to avoid redoing.

Also that registration outputs each AEC channel after masking as a combined TIF file. The issue is that they do not contain any non-AEC channels and that their assignments are as “Stacks” instead of “Channels”.

Aren't the pre-registered png images I have or this combined file sufficient to run this package without realignment?
________________________________

**Comment by Yu-AnChen** [comment]
I see, sorry I misunderstood. Did you do stain separation to extract AEC stains into single channels? What I have done in the past is to run stain separation and generate a stack of separated colors where each channel corresponds to one stain. And I use the generated multichannel TIFF as the input for mcmicro, and the rows in `markers.csv` map to each of the channels.

**Comment by ArtemSokolov** [comment]
@asmagen, when you open `unmicst-1003_bx.ome.tif` in an image viewer (FIJI or Napari), how many channels do you see?

The following format you used is correct:
```
cycle,marker_name
1,CD3
2,CD8
3,FOXP3
4,CD20
```

but MCMICRO is not detecting 4 channels in your image, which is why you are seeing the error.

**Comment by asmagen** [comment]
Where can I find it?
________________________________

**Comment by ArtemSokolov** [comment]
FIJI and Napari are publicly available image viewers that can be downloaded from https://imagej.net/software/fiji/ and https://napari.org/, respectively. The documentation of each viewer can give you more details about loading images, but finding the number of channels in both viewers should be pretty straightforward.

For example, when I process [exemplar-001](https://mcmicro.org/datasets/) with MCMICRO and open `registration/exemplar-001.ome.tif` in FIJI, it presents me with the following menu:

![image](https://user-images.githubusercontent.com/1377144/162542787-9520bf92-ff36-4fb7-9241-62390a62df22.png)

From here, I can tell that the file contains an image pyramid with three levels, and each level contains 12 channels. Since my `.ome.tif` contains 12 channels, the matching `markers.csv` must contain 12 marker names.

**Comment by ArtemSokolov** [comment]
Closing due to inactivity. Please reopen if the issue persists.
