### ISSUE TITLE
OSError: [Errno 28] No space left on device when trying to use mesmer with singularity

### ISSUE THREAD

**Issue by rmontagn** [labsyspharm/mcmicro#468]
Hello,

I am trying run MC-Micro with the segmenter `mesmer` with the profile `singularity`.

However, at segmentation step, I always get the error message:

```
Error executing process > 'segmentation:worker (mesmer-1)'

Caused by:
  Process `segmentation:worker (mesmer-1)` terminated with an error exit status (1)

Command executed:

  python3 /usr/src/app/run_app.py mesmer --squeeze --output-directory . --output-name cell.tif --nuclear-image P39_S48_Tonsil_18p@20220330_144941_582605_2.ome.tif

Command exit status:
  1

Command output:

  16646144/96885295 [====>.........................] - ETA: 36s

Command error:
  2022-12-15 16:06:06.761398: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/lib/python3.8/dist-packages/cv2/../../lib64:/.singularity.d/libs
  2022-12-15 16:06:06.761426: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
  Traceback (most recent call last):
    File "/usr/local/lib/python3.8/dist-packages/keras/utils/data_utils.py", line 85, in urlretrieve
      fd.write(chunk)
  OSError: [Errno 28] No space left on device
  
  During handling of the above exception, another exception occurred:
  
  Traceback (most recent call last):
    File "/usr/src/app/run_app.py", line 60, in <module>
      run_application(dict(ARGS._get_kwargs()))
    File "/usr/src/app/deepcell_applications/app_runners.py", line 52, in run_application
      app = dca.utils.get_app(arg_dict['app'])
    File "/usr/src/app/deepcell_applications/utils.py", line 44, in get_app
      return app_map[name]['class'](**kwargs)
    File "/usr/local/lib/python3.8/dist-packages/deepcell/applications/mesmer.py", line 216, in __init__
      archive_path = tf.keras.utils.get_file(
    File "/usr/local/lib/python3.8/dist-packages/keras/utils/data_utils.py", line 277, in get_file
      urlretrieve(origin, fpath, dl_progress)
    File "/usr/local/lib/python3.8/dist-packages/keras/utils/data_utils.py", line 85, in urlretrieve
      fd.write(chunk)
  OSError: [Errno 28] No space left on device

Work dir:
  /home/remi/Documents/projects/orion/work/94/315d99d560d7b51709db2a7c73db61

Tip: when you have fixed the problem you can continue the execution adding the option `-resume` to the run command line
```

I cannot use another profile than singularity so I really need to find a way to fix it.

I thought that maybe the problem was that mesmer tries to download something, a model I guess, but that the singularity img is not writable. So I tried to create a writable singularity image, ran mesmer in it once and then changed the writeable image into a normal one with the good name so that MC-Micro finds it. But it did not work.

Do you know how I could solve this problem ?

Thank you !

**Comment by ArtemSokolov** [comment]
This may be the same problem as https://github.com/vanvalenlab/deepcell-applications/issues/16#issuecomment-1049773276

@FloWuenne: How did you end up fixing this issue? Did my proposal in https://github.com/vanvalenlab/deepcell-applications/issues/16#issuecomment-1049951285 work for you?

**Comment by rmontagn** [comment]
It worked !

Thank you so much !
