### ISSUE TITLE
quantification:mcquant error after segmentation with Mesmer

### ISSUE THREAD

**Issue by nancyliy** [labsyspharm/mcmicro#475]
I encountered the following error when running the MCMICRO pipeline at the quantification stage of the workflow:

Error executing process > 'quantification:mcquant (1)'

Caused by:
  Process `quantification:mcquant (1)` terminated with an error exit status (1)

Command executed:

  python /app/CommandSingleCellExtraction.py --image pilot_2--mesmer.ome.tif      --masks cell*.tif --output . --channel_names markers.csv

Command exit status:
  1

Command output:
  {'masks': ['cell.tif'], 'image': 'pilot_2--mesmer.ome.tif', 'channel_names': 'markers.csv', 'output': '.', 'intensity_props': {'intensity_mean'}, 'mask_props': None}
  Extracting single-cell data for pilot_2--mesmer.ome.tif...

Command error:
  WARNING: DEPRECATED USAGE: Environment variable SINGULARITYENV_TMPDIR will not be supported in the future, use APPTAINERENV_TMPDIR instead
  INFO:    underlay of /usr/bin/nvidia-smi required more than 50 (434) bind mounts
  Traceback (most recent call last):
  {'masks': ['cell.tif'], 'image': 'pilot_2--mesmer.ome.tif', 'channel_names': 'markers.csv', 'output': '.', 'intensity_props': {'intensity_mean'}, 'mask_props': None}
  Extracting single-cell data for pilot_2--mesmer.ome.tif...
    File "/app/CommandSingleCellExtraction.py", line 11, in <module>
      SingleCellDataExtraction.MultiExtractSingleCells(**args)
    File "/app/SingleCellDataExtraction.py", line 263, in MultiExtractSingleCells
      ExtractSingleCells(masks,image,channel_names,output, mask_props=mask_props, intensity_props=intensity_props)
    File "/app/SingleCellDataExtraction.py", line 236, in ExtractSingleCells
      scdata_z = MaskZstack(masks_loaded,image,channel_names_loaded_checked, mask_props=mask_props, intensity_props=intensity_props)
    File "/app/SingleCellDataExtraction.py", line 145, in MaskZstack
      MaskChannel(masks_loaded[mask_names[nm]],image_loaded_z, intensity_props=intensity_props)
    File "/app/SingleCellDataExtraction.py", line 35, in MaskChannel
      dat = measure.regionprops_table(
    File "/home/users/nancyliy/.local/lib/python3.9/site-packages/skimage/measure/_regionprops.py", line 974, in regionprops_table
      regions = regionprops(label_image, intensity_image=intensity_image,
    File "/home/users/nancyliy/.local/lib/python3.9/site-packages/skimage/measure/_regionprops.py", line 1290, in regionprops
      props = RegionProperties(sl, label, label_image, intensity_image,
    File "/home/users/nancyliy/.local/lib/python3.9/site-packages/skimage/measure/_regionprops.py", line 288, in __init__
      raise ValueError('Label and intensity image shapes must match,'
  ValueError: Label and intensity image shapes must match, except for channel (last) axis.

The input registration image `pilot_2--mesmer.ome.tif` and the output mask `cell*.tif` are too large to be shared here but I am happy to share those files via OneDrive if needed to examine the image shapes.

Thank you!
 
[Nextflow_Pilot2.txt](https://github.com/labsyspharm/mcmicro/files/10492425/Nextflow_Pilot2.txt)

**Comment by ArtemSokolov** [comment]
Hi @nancyliy,

The following error indicates that the input image and the label mask have different dimensions:
> ValueError: Label and intensity image shapes must match, except for channel (last) axis.

What is the width & height of `pilot_2--mesmer.ome.tif` and `cell.tif`? Was there any additional processing done to the images? It would be strange for Mesmer to produce a mask image that has different dimensions than the original image.

**Comment by nancyliy** [comment]
@ArtemSokolov Thanks for your suggestion. I would like to know how to get the dimensions of input `pilot_2--mesmer.ome.tif` and the mask `cell.tif` printed from within the `SingleCellDataExtraction.py` attached here as sanity checks. 

[run_quantifictation.txt](https://github.com/labsyspharm/mcmicro/files/10496518/run_quantifictation.txt)
[CommandSingleCellExtraction.txt](https://github.com/labsyspharm/mcmicro/files/10496523/CommandSingleCellExtraction.txt)
[SingleCellDataExtraction.txt](https://github.com/labsyspharm/mcmicro/files/10496525/SingleCellDataExtraction.txt)

There was no additional processing done to the images beyond MCMICRO pipeline.

Thank you!

**Comment by ArtemSokolov** [comment]
There are a lot of different ways to determine image dimensions, depending on what's installed on your system.

* Most image viewers, like ImageJ, napari, etc., will display the information when you load the image.
* You can install and use `showinf` from bioformats tools (https://docs.openmicroscopy.org/bio-formats/latest/users/comlinetools/display.html) to display basic image information
* You can also `pip install tifffile` and query the dimensions programmatically with

``` python
import tifffile
tifffile.imread('exemplar-001/registration/exemplar-001.ome.tif').shape
# (12, 3139, 2511)
tifffile.imread('exemplar-001/segmentation/mesmer/exemplar-001.ome.tif').shape
# (3139, 2511)
```

In the above example, we can see that the input image contains 12 channels, each channel being a 3139 x 2511 pixel image. Similarly, the segmentation mask is a single-channel 3139 x 2511 pixel image.

**Comment by nancyliy** [comment]
Thanks @ArtemSokolov ! I used your advice I found out my mask has a dimension of (11520, 19392, 2) -- suggesting it has 2 compartments. Then instead of using `--compartment both`, I run the `mcmicro` pipeline on `nuclear` and `whole-cell` separately and that successfully overcame the problem:) A big big thank you to your timely help!
