### ISSUE TITLE
Does this pipeline support PhenoCycler-Fusion Codex format?

### ISSUE THREAD

**Issue by liuyang2006** [labsyspharm/mcmicro#541]
I have a new data format called PhenoCycler-Fusion. Can MIMICRO handle this type of image data (.qptiff)? Thank you!

**Comment by ArtemSokolov** [comment]
Hi @liuyangzzu,

MCMICRO is Bio-Formats compatible: https://bio-formats.readthedocs.io/en/v7.2.0/supported-formats.html
If you instrument adheres to the Bio-Formats standards, MCMICRO should theoretically run on your data.

You can [control what file extensions](https://mcmicro.org/troubleshooting/faq.html#q-mcmicro-doesnt-seem-to-recognize-my-file-format-how-do-i-tell-it-what-files-to-look-for) MCMICRO looks for in your `params.yml`.

**Comment by liuyang2006** [comment]
Hi,

I am working with PhenoCycler-Fusion CODEX image data, specifically *.qptiff files. According to the documentation available at [Bio-Formats Documentation](https://bio-formats.readthedocs.io/en/v7.2.0/formats/vectra-qptiff.html), these files should be compatible with Bio-Formats.

However, I've encountered an issue where the first registration step in your pipeline fails when I attempt to process these files. Could you please let me know if you have any test cases or examples that involve processing this specific type of file? Your guidance on how to successfully navigate this issue would be greatly appreciated.

Thank you in advance.

Best regards,
Yang

**Comment by ArtemSokolov** [comment]
Hi @liuyangzzu,

Can you please share the error message you are getting, as well as your `params.yml`?

We do not have a test case for that particular instrument, but based on the bio-formats documentation, it looks like a multi-file format. Can you try specifying the following in your `params.yml`:

```
workflow:
  multi-formats: qptiff
```

**Comment by liuyang2006** [comment]
Thank you for quick response. My QPTIFF image is a single file contains 41 channels. I got below error message.
```
executor >  local (1)
[-        ] process > illumination                -
[84/271f7e] process > registration:ashlar (1)     [100%] 1 of 1, failed: 1 ✘
[-        ] process > background:backsub          -
[-        ] process > dearray:coreograph          -
[-        ] process > dearray:roadie:runTask      -
[-        ] process > segmentation:roadie:runTask -
[-        ] process > segmentation:worker         -
[-        ] process > segmentation:s3seg          -
[-        ] process > quantification:mcquant      -
[-        ] process > downstream:worker           -
[-        ] process > viz:autominerva             -
Error executing process > 'registration:ashlar (1)'

Caused by:
  Process `registration:ashlar (1)` terminated with an error exit status (1)

Command executed:

  ashlar 'raw/FV_UC-01.qptiff'  -m 30  -o jax_data_test.ome.tif

Command exit status:
  1



  + ashlar raw/FV_UC-01.qptiff -m 30 -o jax_data_test.ome.tif
  WARNING: Stage coordinates undefined; falling back to (0, 0).
  Stitching and registering input images
  Cycle 0:
      reading raw/FV_UC-01.qptiff
  Traceback (most recent call last):
    File "/usr/local/bin/ashlar", line 8, in <module>
      sys.exit(main())
    File "/usr/local/lib/python3.10/dist-packages/ashlar/scripts/ashlar.py", line 226, in main
      return process_single(
    File "/usr/local/lib/python3.10/dist-packages/ashlar/scripts/ashlar.py", line 262, in process_single
      edge_aligner.run()
    File "/usr/local/lib/python3.10/dist-packages/ashlar/reg.py", line 505, in run
      self.check_overlaps()
    File "/usr/local/lib/python3.10/dist-packages/ashlar/reg.py", line 527, in check_overlaps
      for t1, t2 in self.neighbors_graph.edges
    File "/usr/local/lib/python3.10/dist-packages/ashlar/reg.py", line 473, in neighbors_graph
      max_distance = aligner.metadata.size.max() + 1
    File "/usr/local/lib/python3.10/dist-packages/ashlar/reg.py", line 108, in size
      raise ValueError("Image series must all have the same dimensions")
  ValueError: Image series must all have the same dimensions
```

**Comment by jmuhlich** [comment]
Those files are pre-stitched and heavily pre-processed for visual review, not quantification. You can try placing the qptiff in the registration folder and starting mcmicro from segmentation but the quantification results may not be satisfactory due to the pre-processing.

**Comment by liuyang2006** [comment]
Hi,

I have put my QPTIFF files in `registration/` folder, and use `start-at: segmentation` in params.yml file.

But the pipeline failed with error message:

```
 -- Check script '/home/liuya/.nextflow/assets/labsyspharm/mcmicro/main.nf' at line: 88 or see '.nextflow.log' file for more details

[-        ] process > illumination                -
[-        ] process > registration:ashlar         -
[-        ] process > background:backsub          -
[-        ] process > dearray:coreograph          -
[-        ] process > dearray:roadie:runTask      -
[-        ] process > segmentation:roadie:runTask -
[-        ] process > segmentation:worker         -
[-        ] process > segmentation:s3seg          -
[-        ] process > quantification:mcquant      -
[-        ] process > downstream:worker           -
[-        ] process > viz:autominerva             -
No pre-stitched image in /projects/li-lab/yang/codex2/data/jax_data_test/registration

 -- Check script '/home/liuya/.nextflow/assets/labsyspharm/mcmicro/main.nf' at line: 88 or see '.nextflow.log' file for more details
```

**Comment by ArtemSokolov** [comment]
Hi @jmuhlich and @liuyangzzu,

The issue is here: https://github.com/labsyspharm/mcmicro/blob/master/main.nf#L87
It will only look for files with the following extensions in the registration folder: `"*.{ome.tiff,ome.tif,tif,tiff,btf}"`

I am not super familiar with the QPTIFF format. What will happen if you do:
```
import tifffile
img = tifffile.imread('myimage.qptiff', key=0)
```
Will it load the first (in 0-based indexing) channel as expected?

If so, then we can probably just augment that line to also look for `qptiff` files.
If the above doesn't work as expected, then we need to build a bioformats -> .ome.tiff converter for pre-stitched images.

(The `imread()` call above is basically how all downstream modules read individual channels from a stitched and registered OME-TIFF.)

**Comment by daniannr** [comment]
Hi, 
I'm facing the same issue where I'm working with a Phenocycler-fusion output that is a pre-stitched and pre-registered `qptiff` file. Has the team added the `qptiff` format as another file format that is accepted in the registration folder? Would be great to run the pipeline starting from segmentation onwards.

Thanks!

**Comment by ArtemSokolov** [comment]
Hi @daniannr,

Same question. Can you try:

``` python
import tifffile
img = tifffile.imread('myimage.qptiff', key=0)
```

in Python and let me know if it loads the first channel? If so, it's an easy fix to have the pipeline look for `qptiff` files in the registration folder.

**Comment by daniannr** [comment]
Hi @ArtemSokolov ,
Thanks for the quick response. Looks like it did successfully load just the first channel:

<img width="423" alt="Image" src="https://github.com/user-attachments/assets/a65d5961-01e8-4361-b600-eb79df616496" />

**Comment by ArtemSokolov** [comment]
Excellent! Thanks for checking.

I just pushed a small change that will have the pipeline look for qptiff files in the `registration/` subfolder when starting from pre-stitched images.

Can you do `nextflow pull labsyspharm/mcmicro` and try running it with `start-at: segmentation`?

**Comment by daniannr** [comment]
Before doing that, since I'm skipping registration and stitching, what should the markers.csv file look like? I assume it doesn't need the cycle number anymore

**Comment by ArtemSokolov** [comment]
`markers.csv` gets used during quantification to generate a cells by feature table, so that should stay unchanged. (Unless you don't plan on running quantification, in which case, it can be whatever.)

**Comment by daniannr** [comment]
Hi Artem,

I would like to run quantification, but I'm not quite sure what the `markers.csv` file should look like since I don't have information on the cycle number. But mine looks something like this: 
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:////Users/da2655/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip.htm">
<link rel=File-List
href="file:////Users/da2655/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip_filelist.xml">
<style>

</style>
</head>

<body link="#467886" vlink="#96607D">


channel_number | marker_name
-- | --
0 | DAPI
1 | CD8
2 | CD20
3 | HLA-DR
4 | Podoplanin
5 | SMA
6 | CD4
7 | Ki67
8 | AQP1
9 | ICOS



</body>

</html>


Is this the right format and should I start with 1 instead of 0?

Thank you!

**Comment by ArtemSokolov** [comment]
Hi @daniannr,

It can actually just be a single column named `marker_name`:
```
marker_name
DAPI
CD8
CD20
HLA-DR
Podoplanin
...
```

If you do want to specify `channel_number`, MCMICRO's follows 1-based indexing.
Also, make sure to use comma as the delimiter.

**Comment by daniannr** [comment]
Hi @ArtemSokolov ,

Thanks for clarifying! Since this is a TMA, I ran it with `start-at: dearray` and it looks like it errored out during segmentation. Here are my params:
`workflow:
    start-at: dearray
    stop-at: quantification
    tma: true
    segmentation-channel: 1`

I've attached my nextflow.log and job log files here. 

[nextflowlog.txt](https://github.com/user-attachments/files/18623594/nextflowlog.txt)

[serial_test_59181420.log](https://github.com/user-attachments/files/18623598/serial_test_59181420.log)

Another thing – I tried `start-at: background` as well to start with background subtraction, but it couldn't run. I can share my log files for that if you need them.

Thank you!

**Comment by ArtemSokolov** [comment]
Looks like it times out before it finishes converting Docker containers to Singularity:
```
  Failed to pull singularity image
    command: singularity pull  --name labsyspharm-unmicst-2.7.7.img.pulling.1738345218060 docker://labsyspharm/unmicst:2.7.7 > /dev/null
    status : 143
    hint   : Try and increase singularity.pullTimeout in the config (current is "20m")
```

A couple of possible options:
* Pre-pull the containers to some `/path/to/local/folder/` in your filesystem. You can then create a `custom.config` with a single line:
```
singularity.cacheDir  = '/path/to/local/folder/'
```

* Increase the timeout by creating a `custom.config` with the following line
```
singularity.pullTimeout = 60m
```

In both cases, you can provide your `custom.config` to the pipeline with
```
nextflow run labsyspharm/mcmicro --in /path/to/data -c custom.config
```

**Comment by daniannr** [comment]
Hi @ArtemSokolov ,

Thanks for the solution – I managed to run the pipeline from dearray to quantification successfully! Here's what I added to the `custom.config` file I created:
`singularity {
    cacheDir = "/path/to/local/folder/with/containers"
    pullTimeout = '60m'
}`
And I ran it with the `-c custom.config` argument.

I haven't tried running from background subtraction, but I'll let you know if there's any issues when I do. Thank you so much for your help and for your quick responses! Excited to check out the outputs. I believe you can close this issues now :)

**Comment by ArtemSokolov** [comment]
Thanks, @daniannr. Glad to hear it's working! 🚀
