### ISSUE TITLE
s3seg coupled with unmicst work poorly on my images

### ISSUE THREAD

**Issue by emir-radkevich** [labsyspharm/mcmicro#568]
Hi.

I noticed that segmentation result is kind of poor in certain regions in the images generated in my lab.
Attached are qc from unmicst and s3seg.

This is `params.yml` file I am using:
```
workflow:
  start-at: segmentation
  stop-at: segmentation
  segmentation-channel: 1
options:
  unmicst: --scalingFactor 0.5 --tool unmicst-solo
  s3seg: --nucleiRegion localMax
```

I use `scalingFactor 0.5` because the pixel size is 0.325 micrometers in my case. I also do not have staining for nuclear envelope, only Hoechst (first channel in my channels list), that is why I use `unmicst-solo`. 
`--nucleiRegion localMax` works a bit better than default parameter, but still as you can see in screenshots, there are a lot of missed cells, though they are clearly seen in outlined in unmicst output. 

Could it be the intensity issue -- s3seg does not recognize nuclei because they have weak intensity? 
Could you please give me other suggestions?

<img width="1063" alt="Screenshot 2024-12-10 at 1 38 22 PM" src="https://github.com/user-attachments/assets/ff4d4f65-49dc-479d-abb9-ab6c004ed108">
<img width="1063" alt="Screenshot 2024-12-10 at 1 38 34 PM" src="https://github.com/user-attachments/assets/81f2910f-6fe9-4d7f-971d-5f0deb06735a">
<img width="1063" alt="Screenshot 2024-12-10 at 1 38 51 PM" src="https://github.com/user-attachments/assets/edc34513-4df6-462a-87c5-9a0a8e364004">
<img width="1063" alt="Screenshot 2024-12-10 at 1 38 57 PM" src="https://github.com/user-attachments/assets/582ea4e7-fc38-4504-a97a-fee9a79df2f2">

**Comment by ArtemSokolov** [comment]
Hi @emir-radkevich,

@clarenceyapp developed s3seg, so he may be able to provide some suggestions about parameter settings.
You can also try [one of the other segmenters](https://mcmicro.org/parameters/workflow.html#segmentation) to see if they yield better results.

**Comment by emir-radkevich** [comment]
I also would like to add probability maps for unmicst.

<img width="1063" alt="Screenshot 2024-12-10 at 6 49 26 PM" src="https://github.com/user-attachments/assets/e3e1a409-061e-491f-b654-8860a1c518c7">
<img width="1063" alt="Screenshot 2024-12-10 at 6 49 39 PM" src="https://github.com/user-attachments/assets/798616d2-2974-45df-8c2b-2735193380c0">

**Comment by emir-radkevich** [comment]
Hi.

**UPDATE**: I tried stardist in qupath and it works much better. Am I missing something?

<img width="1057" alt="Screenshot 2024-12-19 at 4 07 09 PM" src="https://github.com/user-attachments/assets/e44dad6b-1834-44e2-b5e0-a62f01722705" />
<img width="1057" alt="Screenshot 2024-12-19 at 4 07 19 PM" src="https://github.com/user-attachments/assets/634c05ac-6e04-4425-af54-bcbf5488b477" />

I used this script:

```
/**
 * This script provides a general template for cell detection using StarDist in QuPath.
 * This example assumes you have fluorescence image, which has a channel called 'DAPI' 
 * showing nuclei.
 * 
 * If you use this in published work, please remember to cite *both*:
 *  - the original StarDist paper (https://doi.org/10.48550/arXiv.1806.03535)
 *  - the original QuPath paper (https://doi.org/10.1038/s41598-017-17204-5)
 *  
 * There are lots of options to customize the detection - this script shows some 
 * of the main ones. Check out other scripts and the QuPath docs for more info.
 */

import qupath.ext.stardist.StarDist2D
import qupath.lib.scripting.QP

// IMPORTANT! Replace this with the path to your StarDist model
// that takes a single channel as input (e.g. dsb2018_heavy_augment.pb)
// You can find some at https://github.com/qupath/models
// (Check credit & reuse info before downloading)
def modelPath = "/Users/emir/Documents/qupath_models/dsb2018_heavy_augment.pb"

// Customize how the StarDist detection should be applied
// Here some reasonable default options are specified
def stardist = StarDist2D
    .builder(modelPath)
    .channels('01_Nucleus_Hoechst')            // Extract channel called 'DAPI'
    .normalizePercentiles(1, 99) // Percentile normalization
    .threshold(0.5)              // Probability (detection) threshold
    .pixelSize(0.5)              // Resolution for detection
    //.cellExpansion(5)            // Expand nuclei to approximate cell boundaries
    .measureShape()              // Add shape measurements
    .measureIntensity()          // Add cell measurements (in all compartments)
    .build()
	
// Define which objects will be used as the 'parents' for detection
// Use QP.getAnnotationObjects() if you want to use all annotations, rather than selected objects
//def pathObjects = QP.getSelectedObjects()
def pathObjects = QP.getAnnotationObjects()

// Run detection for the selected objects
def imageData = QP.getCurrentImageData()
if (pathObjects.isEmpty()) {
    QP.getLogger().error("No parent objects are selected!")
    return
}
stardist.detectObjects(imageData, pathObjects)
stardist.close() // This can help clean up & regain memory
println('Done!')
```

**Comment by clarenceyapp** [comment]
Hi Emir,
The unmicst probability maps appear to look ok but some cells do look abit dim but should still be usable. You can try setting the --mean and --std to be lower values such as 0.1 for both to compensate for low signals. We don't typically need to do this.

For s3seg, the most helpful change for your images will likely be step 3 in the tuning page<https://mcmicro.org/troubleshooting/tuning/s3seg> where --logSigma controls the diameter of cells that are being filtered out. If you've had to scale down your image by 0.5x earlier in unmicst, then that implies that your cells have a wider pixel diameter by 2-fold, and so the usable diameter range should be doubled more than default, ie. Instead of 3 to 60, use --logSigma 6 120 to compensate for the finer pixel sizes.

We are working on automating all of this to make parameter tuning more seamless.


Clarence Yapp,  DPhil (Oxon)
Director of Microscopy & Computer Vision
Laboratory of Systems Pharmacology

Harvard Medical School
200 Longwood Avenue
Boston, MA 02115
***@***.******@***.***>


________________________________

**Comment by emir-radkevich** [comment]
Hi Clarence.

Thank you, it sounds logical. 

I have tried adding `--logSigma 6 120` to the s3seg, the results look kind of the same:

<img width="1062" alt="Screenshot 2024-12-24 at 12 06 31 PM" src="https://github.com/user-attachments/assets/ed73a838-9454-49bc-b81b-17566665e169" />
<img width="1062" alt="Screenshot 2024-12-24 at 12 06 51 PM" src="https://github.com/user-attachments/assets/e85cbeee-08f1-434c-bf9f-cd195fec5b6a" />

I also tried setting --mean and --std to 0.1, keeping logSima values high, the results look kind of the same as well. Some cells have been added here and there though:

<img width="1062" alt="Screenshot 2024-12-24 at 12 20 33 PM" src="https://github.com/user-attachments/assets/73ec158a-7acf-4b4b-b468-3da980ebbc5f" />
<img width="1062" alt="Screenshot 2024-12-24 at 12 20 43 PM" src="https://github.com/user-attachments/assets/7276fd69-7284-4917-9b73-95de4cb0e7ed" />

**Comment by clarenceyapp** [comment]
Hi Emir,
I think we will need to run some tests with your images on our side to see what is going on. We can do this once the team is back from holiday.

There is another version of s3seg which handles large images which we are moving towards. This won't solve the problems you've described though but will help with resource allocation.

When you tried --mean and --std 0.1, did the probability maps look better at least, in terms of finding more cells? It's possible to drop mean and std to even as low as 0.07 for very dim images.

Best,
Clarence

Clarence Yapp,  DPhil (Oxon)
Director of Microscopy & Computer Vision
Laboratory of Systems Pharmacology

Harvard Medical School
200 Longwood Avenue
Boston, MA 02115
***@***.******@***.***>


________________________________

**Comment by emir-radkevich** [comment]
Probability maps look much brighter (see attached):

<img width="1058" alt="Screenshot 2025-01-03 at 2 13 23 PM" src="https://github.com/user-attachments/assets/d8819bfc-9940-40cc-8b90-2c7305fbf3bb" />
<img width="1058" alt="Screenshot 2025-01-03 at 2 13 35 PM" src="https://github.com/user-attachments/assets/a1b5a62d-aa49-4b6f-b1e7-a148d65ffee3" />

I also attach the crop image itself (160Mb): https://drive.google.com/file/d/1jWZWhI93d-mg-ms4WUfvn-2Qtu0OsC_f/view?usp=sharing

Thank you for your help.

**Comment by Yu-AnChen** [comment]
Hi @emir-radkevich, thanks for sharing the images. I compiled an image for qualitative comparison of the three segmentation methods: unmicst, stardist, and cellpose: [all-results.ome.tif.zip](https://github.com/user-attachments/files/18326076/all-results.ome.tif.zip), you can open it in QuPath the channel name is indicative. 

- unmicst + s3seg settings can be found [here](https://github.com/Yu-AnChen/dump/blob/cdaa8f5ea1dc658f2edaf46f337d8ea6bfc89634/2025-01/mcmicro-568/config.yml) my experience is that the unmicst-duo model is better at detecting out-of-focus nuclei. And I scaled down the size of the image a bit more (`0.4`) to reduce over-segmentation
- stardist segmentation is done with your script, I convert the polygons to labeled mask to facilitate visual comparison.
- The script for Cellpose is [here](https://github.com/Yu-AnChen/dump/blob/cdaa8f5ea1dc658f2edaf46f337d8ea6bfc89634/2025-01/mcmicro-568/run-cellpose.py). `cyto3` plus `deblur_cyto3` was used. 

To me each method has its strength and weakness. Qualitatively I think the cellpose is the best out of these 3 in the crop you shared.

**Comment by emir-radkevich** [comment]
> Hi @emir-radkevich, thanks for sharing the images. I compiled an image for qualitative comparison of the three segmentation methods: unmicst, stardist, and cellpose: [all-results.ome.tif.zip](https://github.com/user-attachments/files/18326076/all-results.ome.tif.zip), you can open it in QuPath the channel name is indicative.
> 
> * unmicst + s3seg settings can be found [here](https://github.com/Yu-AnChen/dump/blob/cdaa8f5ea1dc658f2edaf46f337d8ea6bfc89634/2025-01/mcmicro-568/config.yml) my experience is that the unmicst-duo model is better at detecting out-of-focus nuclei. And I scaled down the size of the image a bit more (`0.4`) to reduce over-segmentation
> * stardist segmentation is done with your script, I convert the polygons to labeled mask to facilitate visual comparison.
> * The script for Cellpose is [here](https://github.com/Yu-AnChen/dump/blob/cdaa8f5ea1dc658f2edaf46f337d8ea6bfc89634/2025-01/mcmicro-568/run-cellpose.py). `cyto3` plus `deblur_cyto3` was used.
> 
> To me each method has its strength and weakness. Qualitatively I think the cellpose is the best out of these 3 in the crop you shared.

Hi.

Thank you for a such comprehensive and fast response.

I have a few questions:
1. Could you please describe roles of the parameters you added to the s3seg? Or provide a link with descriptions of these parameters?
```
--maxima-footprint-size 13 --area-max 50000 --expand-size 5 --mean-intensity-min 128
```
2. Could these parameters be generalizable for the slides with similar quality? Because we are trying to find some method applicable by default, not changing parameters for each slide.

Again, thank you so much for your help.

**Comment by Yu-AnChen** [comment]
Hi @emir-radkevich, for question 2, I found that the same set of parameters generally works across multiple samples of the same tissue type or disease. However, when using a whole-slide image (rather than a cropped region like the one you shared), I recommend starting with `--outlier 99.95` for `unmicst` instead of `--outlier 99.9`. This is because there are more non-tissue regions in the WSI and lower percentile will have more saturated nuclear pixels after pixel intensity rescaling.

I apologize for the lack of documentation for the parameters. There's a bit of history, but we’ve since developed a version of s3segmenter that handles large images more effectively, which is being specified in this section in the mcmicro configuration yaml (the `1.5.6-large`)

```
modules:
  watershed:
    name: s3seg
    container: labsyspharm/s3segmenter
    version: 1.5.6-large
```
Re: the details of the parameters - here's the help message from the [`watershed` script](https://github.com/HMS-IDAC/S3segmenter/blob/066ce9017d19326c731505ea1f9dba4908118aba/large/watershed.py) in `s3segmenter` (which is essentially a seeded watershed segmentation of the nuclear contour probability map)

```
Watershed segment probability maps

options:
  -h, --help            show this help message and exit
  -i input-file         path of input probability map
  -o output-ome-path    full path to the output ome-tiff file
  --gaussian-sigma GAUSSIAN_SIGMA
                        sigma value to gaussian blur probability map for peak
                        finding (default: 1.0)
  --maxima-h MAXIMA_H   `h` in `skimage.morphology.extrema.h_maxima` (default:
                        0.01)
  --maxima-footprint-size MAXIMA_FOOTPRINT_SIZE
                        size of the square fooptrint used in
                        `skimage.morphology.extrema.h_maxima` (default: 3)
  --overlap-size OVERLAP_SIZE
                        pixels overlapping for block computation (default:
                        128)
  --mean-intensity-min MEAN_INTENSITY_MIN
                        minimal mean intensity in each segmment (default: 128)
  --area-min AREA_MIN   minimal num of pixels (inclusive) in each segmment
                        (default: 10)
  --area-max AREA_MAX   maximal num of pixels (exclusive) in each segmment
                        (default: 500)
  --expand-size EXPAND_SIZE
                        pixels to expand from each segment (default: 0)
  --mcmicro             flag to name output files in mcmicro format (default:
                        False)
  --pixel-size PIXEL_SIZE
                        image pixel size in micron (default: None)
```


- `gaussian-sigma`, `maxima-h`, and `maxima-footprint-size`: These parameters control the preprocessing of the nuclear contour probability map and perform peak detection using [skimage.morphology.h_maxima](https://scikit-image.org/docs/0.19.x/api/skimage.morphology.html#h-maxima). Smaller values result in more segments and smaller segmented objects.

- `area-min` and `area-max` are for filtering out objects based on size, removing objects that are either too small or too large.

- `expand-size`:  This parameter dilates the nuclear mask by a specified number of pixels to create a proxy for the whole-cell mask.

**Comment by emir-radkevich** [comment]
Thank you.
Another question: is it okay, that using parameters you provided I get nucleiRingOutlines.ome.tif file as if I am not running watershed algorithm? Is it because I use two channels?

**Comment by Yu-AnChen** [comment]
I'm not quite sure what you meant. To clarify, the `nucleiRing.ome.tif` is the nucleus mask (with no dilation). It is generated by running watershed segmentation on the nuclear contour probability map (produced by unmicst). If `expand-size` > 0, it will add the dilated mask, which is the `cellRing.ome.tif` file.

**Comment by emir-radkevich** [comment]
> I'm not quite sure what you meant. To clarify, the `nucleiRing.ome.tif` is the nucleus mask (with no dilation). It is generated by running watershed segmentation on the nuclear contour probability map (produced by unmicst). If `expand-size` > 0, it will add the dilated mask, which is the `cellRing.ome.tif` file.

Understood. Thank you.
I will close the issue. 
Feel free to comment or open it if something comes up.

**Comment by emir-radkevich** [comment]
> Hi @emir-radkevich, for question 2, I found that the same set of parameters generally works across multiple samples of the same tissue type or disease. However, when using a whole-slide image (rather than a cropped region like the one you shared), I recommend starting with `--outlier 99.95` for `unmicst` instead of `--outlier 99.9`. This is because there are more non-tissue regions in the WSI and lower percentile will have more saturated nuclear pixels after pixel intensity rescaling.
> 
> I apologize for the lack of documentation for the parameters. There's a bit of history, but we’ve since developed a version of s3segmenter that handles large images more effectively, which is being specified in this section in the mcmicro configuration yaml (the `1.5.6-large`)
> 
> ```
> modules:
>   watershed:
>     name: s3seg
>     container: labsyspharm/s3segmenter
>     version: 1.5.6-large
> ```
> 
> Re: the details of the parameters - here's the help message from the [`watershed` script](https://github.com/HMS-IDAC/S3segmenter/blob/066ce9017d19326c731505ea1f9dba4908118aba/large/watershed.py) in `s3segmenter` (which is essentially a seeded watershed segmentation of the nuclear contour probability map)
> 
> ```
> Watershed segment probability maps
> 
> options:
>   -h, --help            show this help message and exit
>   -i input-file         path of input probability map
>   -o output-ome-path    full path to the output ome-tiff file
>   --gaussian-sigma GAUSSIAN_SIGMA
>                         sigma value to gaussian blur probability map for peak
>                         finding (default: 1.0)
>   --maxima-h MAXIMA_H   `h` in `skimage.morphology.extrema.h_maxima` (default:
>                         0.01)
>   --maxima-footprint-size MAXIMA_FOOTPRINT_SIZE
>                         size of the square fooptrint used in
>                         `skimage.morphology.extrema.h_maxima` (default: 3)
>   --overlap-size OVERLAP_SIZE
>                         pixels overlapping for block computation (default:
>                         128)
>   --mean-intensity-min MEAN_INTENSITY_MIN
>                         minimal mean intensity in each segmment (default: 128)
>   --area-min AREA_MIN   minimal num of pixels (inclusive) in each segmment
>                         (default: 10)
>   --area-max AREA_MAX   maximal num of pixels (exclusive) in each segmment
>                         (default: 500)
>   --expand-size EXPAND_SIZE
>                         pixels to expand from each segment (default: 0)
>   --mcmicro             flag to name output files in mcmicro format (default:
>                         False)
>   --pixel-size PIXEL_SIZE
>                         image pixel size in micron (default: None)
> ```
> 
> * `gaussian-sigma`, `maxima-h`, and `maxima-footprint-size`: These parameters control the preprocessing of the nuclear contour probability map and perform peak detection using [skimage.morphology.h_maxima](https://scikit-image.org/docs/0.19.x/api/skimage.morphology.html#h-maxima). Smaller values result in more segments and smaller segmented objects.
> * `area-min` and `area-max` are for filtering out objects based on size, removing objects that are either too small or too large.
> * `expand-size`:  This parameter dilates the nuclear mask by a specified number of pixels to create a proxy for the whole-cell mask.

Hi Yu-An.

I am trying to use these parameters for WSI:
```
workflow:
  start-at: segmentation
  stop-at: downstream
  downstream: [scanpy, scimap]
  segmentation-channel: 1 1
options:
  unmicst: --tool unmicst-duo --scalingFactor 0.4 --outlier 99.95
  s3seg: --maxima-footprint-size 13 --area-max 50000 --expand-size 5 --pixelSize 0.325 --mean-intensity-min 128
modules:
  watershed:
    name: s3seg
    container: labsyspharm/s3segmenter
    version: 1.5.6-large
```

And getting strange error during s3seg, have never seen it before:
```
executor >  lsf (2)
[-        ] staging:phenoimager2mc         -
[-        ] illumination                   -
[-        ] registration:ashlar            -
[-        ] background:backsub             -
[-        ] dearray:coreograph             -
[-        ] dearray:roadie:runTask         -
[-        ] segmentation:roadie:runTask    -
[49/5e30de] seg…ntation:worker (unmicst-1) | 1 of 1 ✔
[41/5f3b5e] segmentation:s3seg (1)         | 1 of 1, failed: 1 ✘
[-        ] quantification:mcquant         -
[-        ] downstream:worker              -
[-        ] viz:autominerva                -
ERROR ~ Error executing process > 'segmentation:s3seg (1)'

Caused by:
  Process `segmentation:s3seg (1)` terminated with an error exit status (1)


Command executed:

  python /app/S3segmenter.py         --imagePath HIMC_52231_Ovarian_200x_MSSM_EM_Q143_BV_Test_000226.ome.tiff --stackProbPath HIMC_52231_Ovarian_200x_MSSM_EM_Q143_BV_Test_000226_Probabilities_1.tif         --probMapChan 1   --maxima-footprint-size 13 --area-max 50000 --expand-size 5 --pixelSize 0.325 --mean-intensity-min 128 --outputPath .

Command exit status:
  1

Command output:
  (empty)

Command error:
  Assembling mosaic  1/ 1 (channel  1/ 1): 100%|#########9| 150520/151029 [1:29:10<00:03, 132.39it/s]
  Assembling mosaic  1/ 1 (channel  1/ 1): 100%|#########9| 150541/151029 [1:29:10<00:03, 151.28it/s]
  Assembling mosaic  1/ 1 (channel  1/ 1): 100%|#########9| 150557/151029 [1:29:10<00:03, 151.27it/s]
  Assembling mosaic  1/ 1 (channel  1/ 1): 100%|#########9| 150573/151029 [1:29:11<00:03, 148.42it/s]
  Assembling mosaic  1/ 1 (channel  1/ 1): 100%|#########9| 150588/151029 [1:29:11<00:03, 137.57it/s]
  Assembling mosaic  1/ 1 (channel  1/ 1): 100%|#########9| 150605/151029 [1:29:11<00:02, 143.58it/s]
  Assembling mosaic  1/ 1 (channel  1/ 1): 100%|#########9| 150627/151029 [1:29:11<00:02, 161.40it/s]
  Assembling mosaic  1/ 1 (channel  1/ 1): 100%|#########9| 150645/151029 [1:29:11<00:02, 165.16it/s]
  Assembling mosaic  1/ 1 (channel  1/ 1): 100%|#########9| 150662/151029 [1:29:11<00:02, 165.21it/s]
  Assembling mosaic  1/ 1 (channel  1/ 1): 100%|#########9| 150679/151029 [1:29:11<00:02, 158.50it/s]
  Assembling mosaic  1/ 1 (channel  1/ 1): 100%|#########9| 150700/151029 [1:29:11<00:01, 172.24it/s]
  Assembling mosaic  1/ 1 (channel  1/ 1): 100%|#########9| 150721/151029 [1:29:11<00:01, 173.38it/s]
  Assembling mosaic  1/ 1 (channel  1/ 1): 100%|#########9| 150741/151029 [1:29:12<00:01, 179.66it/s]
  Assembling mosaic  1/ 1 (channel  1/ 1): 100%|#########9| 150760/151029 [1:29:12<00:01, 170.11it/s]
  Assembling mosaic  1/ 1 (channel  1/ 1): 100%|#########9| 150780/151029 [1:29:12<00:01, 177.40it/s]
  Assembling mosaic  1/ 1 (channel  1/ 1): 100%|#########9| 150801/151029 [1:29:12<00:01, 183.69it/s]
  Assembling mosaic  1/ 1 (channel  1/ 1): 100%|#########9| 150823/151029 [1:29:12<00:01, 191.34it/s]
  Assembling mosaic  1/ 1 (channel  1/ 1): 100%|#########9| 150843/151029 [1:29:12<00:01, 181.21it/s]
  Assembling mosaic  1/ 1 (channel  1/ 1): 100%|#########9| 150865/151029 [1:29:12<00:00, 189.24it/s]
  Assembling mosaic  1/ 1 (channel  1/ 1): 100%|#########9| 150885/151029 [1:29:12<00:00, 189.37it/s]
  Assembling mosaic  1/ 1 (channel  1/ 1): 100%|#########9| 150905/151029 [1:29:12<00:00, 177.40it/s]
  Assembling mosaic  1/ 1 (channel  1/ 1): 100%|#########9| 150923/151029 [1:29:13<00:00, 171.96it/s]
  Assembling mosaic  1/ 1 (channel  1/ 1): 100%|#########9| 150941/151029 [1:29:13<00:00, 171.87it/s]
  Assembling mosaic  1/ 1 (channel  1/ 1): 100%|#########9| 150963/151029 [1:29:13<00:00, 183.77it/s]
  Assembling mosaic  1/ 1 (channel  1/ 1): 100%|#########9| 150982/151029 [1:29:13<00:00, 158.92it/s]
  Assembling mosaic  1/ 1 (channel  1/ 1): 100%|#########9| 151001/151029 [1:29:13<00:00, 164.93it/s]
  Assembling mosaic  1/ 1 (channel  1/ 1): 100%|#########9| 151021/151029 [1:29:13<00:00, 171.85it/s]
  Assembling mosaic  1/ 1 (channel  1/ 1): 100%|##########| 151029/151029 [1:29:13<00:00, 28.21it/s]
  Traceback (most recent call last):
    File "/opt/conda/lib/python3.10/site-packages/tifffile/tifffile.py", line 16032, in __getitem__
  ImportError: cannot import name '_imagecodecs' from 'tifffile' (/opt/conda/lib/python3.10/site-packages/tifffile/__init__.py)


  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
    File "/opt/conda/lib/python3.10/site-packages/tifffile/tifffile.py", line 16034, in __getitem__
  ModuleNotFoundError: No module named '_imagecodecs'

  The above exception was the direct cause of the following exception:

  Traceback (most recent call last):
    File "/app/S3segmenter.py", line 104, in <module>
    File "/app/S3segmenter.py", line 80, in main
    File "/app/watershed.py", line 438, in main
    File "/app/watershed.py", line 134, in write
    File "/opt/conda/lib/python3.10/site-packages/palom/pyramid.py", line 176, in write_pyramid
    File "/opt/conda/lib/python3.10/site-packages/tifffile/tifffile.py", line 3085, in write
    File "/opt/conda/lib/python3.10/site-packages/tifffile/tifffile.py", line 16117, in __getitem__
  KeyError: "<COMPRESSION.ADOBE_DEFLATE: 8> requires the 'imagecodecs' package"
  INFO:    Cleaning up image...
```

`.command.log`:
```
WARNING: Could not find any nv files on this host!
INFO:    Converting SIF file to temporary sandbox...
2025-01-09 17:01:40 | INFO     | Pixel size: 0.325 (user supplied) (S3segmenter.py:69)
2025-01-09 17:01:40 | INFO     | Reading HIMC_52231_Ovarian_200x_MSSM_EM_Q143_BV_Test_000226_Probabilities_1.tif (watershed.py:410)
2025-01-09 17:01:40.970 | WARNING  | palom.reader:auto_format_pyramid:64 - Unable to detect pyramid levels, it may take a while to compute thumbnails during coarse alignment
2025-01-09 17:02:21 | INFO     | Probability map shape: (2, 61855, 84231) (watershed.py:412)
2025-01-09 17:02:27 | INFO     | Run initiating (watershed.py:106)
2025-01-09 17:02:27 | INFO     | Configuration:

{'area_max': 50000,
 'area_min': 10,
 'footprint_size': 13,
 'h': 0.01,
 'mean_intensity_min': 128.0,
 'overlap_size': 128,
 'sigma': 1.0}

 (watershed.py:107)
2025-01-09 17:02:27 | INFO     | Start configuring `label` (watershed.py:210)
2025-01-09 17:03:20 | INFO     | End configuring `label` (watershed.py:212)
2025-01-09 17:03:20 | INFO     | Start configuring `label` (watershed.py:113)
2025-01-09 17:07:25 | INFO     | End configuring `label` (watershed.py:115)
2025-01-09 17:07:25 | INFO     | Writing to HIMC_52231_Ovarian_200x_MSSM_EM_Q143_BV_Test_000226/nucleiRing.ome.tif (watershed.py:130)
2025-01-09 17:07:25.284 | INFO     | palom.pyramid:write_pyramid:167 - Writing to HIMC_52231_Ovarian_200x_MSSM_EM_Q143_BV_Test_000226/nucleiRing.ome.tif

<assembling mosaic errors>

Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/tifffile/tifffile.py", line 16032, in __getitem__
ImportError: cannot import name '_imagecodecs' from 'tifffile' (/opt/conda/lib/python3.10/site-packages/tifffile/__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/tifffile/tifffile.py", line 16034, in __getitem__
ModuleNotFoundError: No module named '_imagecodecs'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/S3segmenter.py", line 104, in <module>
  File "/app/S3segmenter.py", line 80, in main
  File "/app/watershed.py", line 438, in main
  File "/app/watershed.py", line 134, in write
  File "/opt/conda/lib/python3.10/site-packages/palom/pyramid.py", line 176, in write_pyramid
  File "/opt/conda/lib/python3.10/site-packages/tifffile/tifffile.py", line 3085, in write
  File "/opt/conda/lib/python3.10/site-packages/tifffile/tifffile.py", line 16117, in __getitem__
KeyError: "<COMPRESSION.ADOBE_DEFLATE: 8> requires the 'imagecodecs' package"
INFO:    Cleaning up image...
```

**Comment by Yu-AnChen** [comment]
Hi @emir-radkevich, my apologies for missing your message. It looks like something was changed on the docker/CI end and possible broke the docker image on docker hub. Could you try the downgrading `1.5.6-large` to `1.5.4-large` in the following section of the params.yml file?

```yaml
modules:
  watershed:
    name: s3seg
    container: labsyspharm/s3segmenter
    version: 1.5.6-large
```
