### ISSUE TITLE
Issue with o2 conda environment

### ISSUE THREAD

**Issue by DenisSch** [labsyspharm/mcmicro#86]
@ArtemSokolov I am getting issues after provenance
```
Command error:
  Traceback (most recent call last):
    File "/n/groups/lsp/mcmicro/2020-04-07/UnMicst/UnMicst.py", line 14, in <module>
      from toolbox.imtools import *
    File "/n/groups/lsp/mcmicro/2020-04-07/UnMicst/toolbox/imtools.py", line 1, in <module>
      import matplotlib.pyplot as plt
    File "/n/scratch2/ds230/example_mcmicro/work/conda/unmicst-fd23057379ebdf6804bf723a9b5c3328/lib/python3.6/site-packages/matplotlib/pyplot.py", line 2282, in <module>
      switch_backend(rcParams["backend"])
    File "/n/scratch2/ds230/example_mcmicro/work/conda/unmicst-fd23057379ebdf6804bf723a9b5c3328/lib/python3.6/site-packages/matplotlib/__init__.py", line 832, in __getitem__
      plt.switch_backend(rcsetup._auto_backend_sentinel)
    File "/n/scratch2/ds230/example_mcmicro/work/conda/unmicst-fd23057379ebdf6804bf723a9b5c3328/lib/python3.6/site-packages/matplotlib/pyplot.py", line 213, in switch_backend
      switch_backend("agg")
    File "/n/scratch2/ds230/example_mcmicro/work/conda/unmicst-fd23057379ebdf6804bf723a9b5c3328/lib/python3.6/site-packages/matplotlib/pyplot.py", line 221, in switch_backend
      backend_mod = importlib.import_module(backend_name)
    File "/n/scratch2/ds230/example_mcmicro/work/conda/unmicst-fd23057379ebdf6804bf723a9b5c3328/lib/python3.6/importlib/__init__.py", line 126, in import_module
      return _bootstrap._gcd_import(name[level:], package, level)
    File "/n/scratch2/ds230/example_mcmicro/work/conda/unmicst-fd23057379ebdf6804bf723a9b5c3328/lib/python3.6/site-packages/matplotlib/backends/backend_agg.py", line 50, in <module>
      from PIL import Image
    File "/n/app/OMERO.server/5.4.10.65-gs-ice36/lib/python2.7/site-packages/PIL/Image.py", line 56, in <module>
      from . import _imaging as core
  ImportError: dynamic module does not define module export function (PyInit__imaging)

Work dir:

/n/scratch2/ds230/example_mcmicro/work/70/02d55b0145f15c79c69459305e4552
```

**Comment by DenisSch** [comment]
@clarenceyapp Looking at this closer it could also be an issue with unmicst?

**Comment by ArtemSokolov** [comment]
Did this run yesterday?

(I don't think this has to do with provenance, since that's a completely independent process and doesn't require conda.)

**Comment by clarenceyapp** [comment]
i think the PIL library isn't loading into the environment. Can you try it again, @DenisSch ?

**Comment by DenisSch** [comment]
I also get this warning FYI:
```
Creating Conda env: /home/ds230/.nextflow/assets/labsyspharm/mcmicro-nf/conda/unmicst.yml [cache /n/scratch2/ds230/work/conda/unmicst-fd23057379ebdf6804bf723a9b5c3328]
WARN: Process 'provenance' cannot be executed by 'slurm' executor -- Using 'local' executor instead
```

I am running exemplar now again

**Comment by DenisSch** [comment]
@clarenceyapp Same error in exemplar. @ArtemSokolov It was all working this morning

> i think the PIL library isn't loading into the environment. Can you try it again, @DenisSch ?

What does this mean? Where should I load it?

**Comment by clarenceyapp** [comment]
@DenisSch can you resubmit the job? If the PIL library is still giving problems, i can get rid of it. It's a leftover library i used to use.

**Comment by DenisSch** [comment]
@clarenceyapp What did you change?

**Comment by ArtemSokolov** [comment]
> WARN: Process 'provenance' cannot be executed by 'slurm' executor -- Using 'local' executor instead

This will go away when we merge the pending pull request. There's a fix addressing this warning.

The provenance process just writes all parameters out to `qc/params.txt`. It does it directly inside nextflow without any need for Conda or SLURM.

**Comment by ArtemSokolov** [comment]
Running exemplar-001 now to see if I can replicate.

**Comment by ArtemSokolov** [comment]
BTW, nothing changed for UnMicst. The pipeline still uses v1.0.0.

**Comment by ArtemSokolov** [comment]
My guess is that it's a corrupted conda environment again.

**Comment by DenisSch** [comment]
@ArtemSokolov It finished for you without issues?

**Comment by ArtemSokolov** [comment]
@DenisSch Did having pre-installed Conda environments address this issue?

**Comment by DenisSch** [comment]
@ArtemSokolov Yes, it works!
